version: "3"
services:
  neo4j:
    image: plantrip_neo4j:1.0.0
    build: ./neo4j
    volumes:
      - /media/diana/DATA/2024/datatourisme/region_idf:/data
  fastapi:
    image: plantrip_fastapi:1.0.0
    build: ./fastapi
    environment:
      NEO4J_URI: "bolt://neo4j:7687"
    ports:
    - 8000:80